### ISSUE TITLE
Implementation of correct number of samples

### ISSUE THREAD

**Issue by winycg** [xuguodong03/SSKD#1]
Hi, I look your implementation of counting correct number of augmented samples in student.py

254-tmp = torch.nonzero(rank, as_tuple=True)[0]
255-correct_num = tmp.numel()

Why I think correct_num  represents the incorrect samples?
Thanks!

**Comment by xuguodong03** [comment]
Thank you for pointing the bugs!
tmp.numel() does represent the incorrect samples. This may be the typo when I re-organised the code. And I have fixed it.
