### ISSUE TITLE
Implementation of data augmentations of self-supervised tasks

### ISSUE THREAD

**Issue by winycg** [xuguodong03/SSKD#2]
Hi, I find four augmentations are used in your manuscript, but the implementation may only include rotation, so I would like to know the reported results derived from only rotation or above four augmentations？

Thanks！

**Comment by xuguodong03** [comment]
Hi there, thanks for the questions. 

The results in paper are derived from four augmentations. But we also found that, the influences of four augmentations are not the same. Rotation plays a main role and the effects of other three are not as crucial as rotation. In implementation, we only include rotation, and its results are nearly the same as that in paper (may have a tiny difference in some teacher-student pairs).

**Comment by winycg** [comment]
Thank you for your response,I get！
