### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by why228430** [xuguodong03/SSKD#4]
Thanks for you sharing the code! when I run student code, I meet the follow problem. How I can do to solve this problem.

(base) C:\Users\11619\Desktop\SSKD-master> python student.py --t-path ./experiments/teacher_wrn_40_2_seed0/ --s-arch wrn_16_2 --lr 0.05 --gpu-id 0
Traceback (most recent call last):
  File "student.py", line 72, in <module>
    os.makedirs(exp_path, exist_ok=True)
  File "D:\anaconda3\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\anaconda3\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\anaconda3\lib\os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 3 more times]
  File "D:\anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './experiments/sskd_student_wrn_16_2_weight0.1+0.9+2.7+10.0_T4.0+4.0+0.5_ratio1.0+0.75_seed0_C:'

**Comment by xuguodong03** [comment]
The directory name is in Linux format, namely directory name is linked with '/'. In Windows, it is '\\'. This repo is highly recommended to be run on Linux. It is not tested on Windows.
